wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.12
    cli_version: 0.14.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1688449849.281813
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 13
      - 23
      4: 3.8.12
      5: 0.14.2
      8:
      - 5
